export const POLKADOT_NAMESPACE = "polkadot";
export const POLKADOT_REFERENCE = "b0a8d493285c2df73290dfb7e61f870f";
export const POLKADOT_CHAIN_ID = `${POLKADOT_NAMESPACE}:${POLKADOT_REFERENCE}`;
export const POLKADOT_ADDRESS = `5hmuyxw9xdgbpptgypokw4thfyoe3ryenebr381z9iaegmfy`;
export const POLKADOT_CAIP10_PARAMS = { chainId: POLKADOT_CHAIN_ID, address: POLKADOT_ADDRESS };
export const POLKADOT_CAIP10_ACCOUNT = `${POLKADOT_CHAIN_ID}:${POLKADOT_ADDRESS}`;
export const POLKADOT_CAIP50_ACCOUNT =
  "zR9TdFW3PkpzbYD9S5umJqWC6BDucP8u8p818NAHgoTVDhrxPzW2J74Jsv9i5ENf5oMWA6PfPV2vHgA";
